name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Image
        run: docker build . --file Dockerfile --tag toolbox:latest
      - name: Tag Image
        uses: actions/docker/tag@master
        args: "--no-ref toolbox:latest jdharrington/toolbox"
      - name: Push Image to DockerHub
        uses: actions/docker/cli@master
        args: "push jdharrington/toolbox:latest"
